# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('yc_class', models.CharField(max_length=10)),
                ('status', models.CharField(default='', max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
