# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trends', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
