# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 02:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trends', '0003_auto_20160415_1820'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('service_type', models.CharField(max_length=200)),
                ('startups', models.ManyToManyField(to='trends.Startup')),
            ],
        ),
    ]
