# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 21:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trends', '0004_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('startups', models.ManyToManyField(to='trends.Startup')),
            ],
        ),
        migrations.RemoveField(
            model_name='service',
            name='service_type',
        ),
        migrations.RemoveField(
            model_name='service',
            name='startups',
        ),
        migrations.AddField(
            model_name='service',
            name='technologies',
            field=models.ForeignKey(default=datetime.datetime(2016, 4, 19, 21, 50, 52, 465000, tzinfo=utc), on_delete=django.db.models.deletion.CASCADE, to='trends.Technology'),
            preserve_default=False,
        ),
    ]
